[firebase]
type = "service_account"
project_id = "gold-rush-5b283"
private_key_id = "ab0e703a1bb9bb598dc235f0896f4a0b26aef3d8"
client_email = "firebase-adminsdk-fbsvc@gold-rush-5b283.iam.gserviceaccount.com"
client_id = "101875462485554933971"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40gold-rush-5b283.iam.gserviceaccount.com"

# AQUI ESTÁ A CHAVE CORRIGIDA (COM QUEBRAS REAIS)
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDoB85sJNtn3Ghf
GGgLIlHH5NG49TjmkEoiZA89Ovqj5oaxowkrEQiNpE3IktRNoEAbsDgph1ymYUs4
Eo84cJRxa78uCnGsvc7koYswQfAmAGTuPp6h7+qPG2yi/E/EiOsL9Wg4dVu2vMQh
U0F4oxoJCaJcfhAeUDlyVbQcQ2TeRQ89mVCh7MWJVmMPppoKQRkBSQufjvF00FlM
erIWGvN7lYScs8slJQQwWZ7s84fGd3oSwFETgi/Z3kQYOsG/nK8OzPEpu2ZYbsAZ
SuKMg/zDvbpeBK+uK1DMKrZCXHJBEhYCOJese++X2J5FLOY3Q9CQnboIRZ/3C42a
IC+UrEmvAgMBAAECggEAJzXigU39MeECVkemlXMYROJ7OnleQ0BQ9tzX4m4MGxSC
4JP/oaKAQodoiaOecvvIuaUe6I2yb39zmacxQsVroHsn1Jz5NsrgoqxV/DK4ZYOd
itFUN2N2zPZCdoyS4lCM//lZwmi6tffSYRtTrhJJ/Qr+wAihqq29939aL4iIDDNn
BC9UPxeDr36jJX1cWsZMJgH1SLtaqtD5NKspqmAoDgZwDn3hu2d79gal7RohIont
k89OEZInKOvSDH1RFDj6XB8Wy82/vIQgAivN7prVIN0fVEb11rT+uzTLCGV+IsA2
vG5CCqjeyX+LLVkHL+2mph7aE8tlZ2Uojr5g6mkL0QKBgQD7yoqBqCIijJEOMvoH
JvxyUlXRwxmHwUrb2RYX6w2aEen7tC9a2BVGam5NySTHjV6qGb8TC7/lSKDBxdSi
fEEgNat8D/zsF53A/HYclRSXo8dQtLIZExQ3RBEE8i4Z+0bxSyQFxLVmwAD5E96q
ztXKGgSzV9txGRW4q1HCAXiZ6QKBgQDr6LSyHku9YnhMDV2vemE5Ij7xxbLX+sVD
n/8kaEPeLo2lIir6XG2UjAxHvN/rgJFDOxISq1ECoaEc4rK8UWMgVRwepwjBz72L
aiHn9Z1OzXtjvBXcuMAzKWK1MTHSqV2LGaqfVlBn6y6cpHvHlDyXfir+WkzMlhsA
gdHtIQ9v1wKBgQCKWmmvAt720vxlq/cc9PwkKT/Eygp+QOTMVsXAEMVhklRanVCj
/zX5gkPn9A2EpRaOKyWF5p/j8ft7XiQPwGzcsQDwY6ybYgKp509TN0ugYzsDCrcN
9iDWmU0sxZI1bpA1yA8cKFFxCzG9q4BfpNVufst0bGNFCv6XgXOkQcCt+QKBgAKI
vWgsayPdqu0mN5tq9SBn/cUbGpC3YOcZEOSTOido2JytgUivNX4jAv7CSKV+/BB8
0fThYj1k/xYQWVsshKQURfkOUknCsYaN3U9glBAEpQ6tNo7obSgfia/ol2Br8VVN
MUgE5Vg4bofAPJQoQ35dHJke3zRTaHbY7ihd8oyBAoGBAOdswfoW1cAWmATKr7Zz
oHDxq3109FsuZhue1ecrCVo5puYLciyOUZmbBPINkh3dc4dnHcfuPgG7225WkaU7
asbo1Qz+4PBA3vVnU0VGH/8LY1z1FCeZ78LRRPg2byHePcwaSU7qe+9v+Jq9QQaZ
k1cuQ5NxdtjA8NTiM/aZe6r6
-----END PRIVATE KEY-----"""

[users]
    [users.admin_gold]
    name = "Gold Rush Admin"
    password = "admin123"
    role = "admin"

    [users.cliente_01]
    name = "Indústria Plásticos ABC"
    password = "cliente123"
    role = "client"